# Generated by Django 2.2.6 on 2019-10-12 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=10)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ATC.Airport')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('isATC', models.BooleanField(default=False)),
                ('isGate', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ATC.Role')),
            ],
        ),
        migrations.CreateModel(
            name='Runway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=10)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ATC.Airport')),
            ],
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=10)),
                ('currentPassengerCount', models.IntegerField()),
                ('maxPassengerCount', models.IntegerField()),
                ('airline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ATC.Airline')),
                ('gate', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ATC.Gate')),
                ('runway', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ATC.Runway')),
            ],
        ),
        migrations.AddField(
            model_name='airline',
            name='airport',
            field=models.ManyToManyField(to='ATC.Airport'),
        ),
    ]
