# Generated by Django 2.2.5 on 2019-09-08 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_assigned',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
